Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12707b880>: Failed to establish a new connection: [Errno 61] Connection refused')': /apis/apps/v1/namespaces/default/deployments
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12707bac0>: Failed to establish a new connection: [Errno 61] Connection refused')': /apis/apps/v1/namespaces/default/deployments
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12707bc70>: Failed to establish a new connection: [Errno 61] Connection refused')': /apis/apps/v1/namespaces/default/deployments
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12789b940>: Failed to establish a new connection: [Errno 61] Connection refused')': /apis/apps/v1/namespaces/default/deployments
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12789bb80>: Failed to establish a new connection: [Errno 61] Connection refused')': /apis/apps/v1/namespaces/default/deployments
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12789bd30>: Failed to establish a new connection: [Errno 61] Connection refused')': /apis/apps/v1/namespaces/default/deployments
